name: PowerWarden CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test & Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get Dependencies
        run: flutter pub get

      - name: Run Dart Analyze
        run: dart analyze

      - name: Run Unit Tests
        run: flutter test

      - name: Build Android APK
        run: flutter build apk --debug
